/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-05-04 10:26:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.admin.page.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    <title>top</title>\r\n");
      out.write("\t<link name=\"pageCss\" rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("app/admin/page/web/css/gsk_common.css\">\r\n");
      out.write("\t<link name=\"pageCss\" id=\"change_style\" rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("app/admin/page/web/css/01/style.css\">\r\n");
      out.write("\t<link name=\"pageCss\" rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(basePath);
      out.write("app/admin/page/web/css/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("  <body>\r\n");
      out.write("              <div>\r\n");
      out.write("              <div id=\"frame2XDKSX_left\" class=\"w100b list_second ui-sortable\">\r\n");
      out.write("                <div systemcomlibid=\"com_8\" id=\"lib_1397488745606\"  class=\"basic_list conner_5\" title=\"图片\" dragtype=\"lib_1397488745606\" type=\"image\" statictype=\"1\">\r\n");
      out.write("                  <div class=\"com_content\">\r\n");
      out.write("                    <div style=\"overflow:hidden;\"> <img src=\"");
      out.print(basePath);
      out.write("app/admin/page/web/images/top01.png\" border=\"0\" height=\"155\" width=\"1007\"> </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"border: medium none; background: none repeat scroll 0% 0% transparent;\" id=\"lay7DNYET\" class=\"div-state-default w100b list_main\">\r\n");
      out.write("              <div id=\"frame7DNYET_left\" class=\"w100b list_second ui-sortable\">\r\n");
      out.write("                <div systemcomlibid=\"com_7\" id=\"lib_1397488814550\" style=\"background-color: transparent; left: 0px; top: 0px; height: 100%;\" class=\"basic_list conner_5\" dragtype=\"lib_1397488814550\" type=\"navigation\" statictype=\"0\">\r\n");
      out.write("                  <div class=\"com_content\">\r\n");
      out.write("                    <div class=\"nav\" style=\"background-repeat: no-repeat;background-image:url();\">\r\n");
      out.write("                       <div class=\"tac\">\r\n");
      out.write("                              <a href=\"");
      out.print(basePath);
      out.write("baseInfo/webindex/list\" style=\"background-repeat: no-repeat;background-image:url(;)\">首页</a>\r\n");
      out.write("                              <span class=\"splitLine\"></span>\r\n");
      out.write("                              <a href=\"");
      out.print(basePath);
      out.write("baseInfo/dish/listIFrameWeb\" style=\"background-repeat: no-repeat;background-image:url(;)\">优秀菜品</a>\r\n");
      out.write("                              <span class=\"splitLine\"></span>\r\n");
      out.write("                              <a href=\"");
      out.print(basePath);
      out.write("baseInfo/kitchener/listIFrameWeb\" style=\"background-repeat: no-repeat;background-image:url(;)\">优秀厨师</a>\r\n");
      out.write("                              <span class=\"splitLine\"></span>\r\n");
      out.write("                              <a href=\"");
      out.print(basePath);
      out.write("baseInfo/cookbook/listIFrameWeb\" style=\"background-repeat: no-repeat;background-image:url(;)\">下周菜谱</a>\r\n");
      out.write("                              <span class=\"splitLine\"></span>\r\n");
      out.write("                              <a href=\"");
      out.print(basePath);
      out.write("baseInfo/purchaseplan/webList\" style=\"background-repeat: no-repeat;background-image:url(;)\">采购公开</a>\r\n");
      out.write("                       </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
